server:
  port: 4004

jwt:
  secret: ${JWT_SECRET:dev-dev-dev-dev-dev-dev-dev-dev-dev-dev-dev-dev}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://auth-service:4005
              predicates:
                - Path=/api/auth/**
              filters:
                - StripPrefix=2

            - id: patient-service-route
              uri: http://patient-service:4000
              predicates:
                - Path=/api/patients/**
              filters:
                - StripPrefix=1

            - id: api-docs-patient-route
              uri: http://patient-service:4000
              predicates:
                - Path=/api-docs/patients,/v3/api-docs

            - id: api-docs-auth-route
              uri: http://auth-service:4005
              predicates:
                - Path=/api-docs/auth,/v3/api-docs

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: DEBUG